// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy7ZZn5nEBV6RRMoTqYLR8UPsX2IciqvY',
    appId: '1:74385235914:web:e2964f79ee8dd93c04f933',
    messagingSenderId: '74385235914',
    projectId: 'athletic-shop',
    authDomain: 'athletic-shop.firebaseapp.com',
    storageBucket: 'athletic-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZyKwJhiDQkDvYokdYQmitLSDJf6iqKX4',
    appId: '1:74385235914:android:8f1d939e5a59c77404f933',
    messagingSenderId: '74385235914',
    projectId: 'athletic-shop',
    storageBucket: 'athletic-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp59BhrFWyjDtZbC2UJiXo4mSGwmCw_uw',
    appId: '1:74385235914:ios:df9819d33f88b1c704f933',
    messagingSenderId: '74385235914',
    projectId: 'athletic-shop',
    storageBucket: 'athletic-shop.appspot.com',
    androidClientId: '74385235914-o9avd5lqi7b42tf95k0afa5ao3gvl6m4.apps.googleusercontent.com',
    iosClientId: '74385235914-1plfq5j691gcvt4851prnjtgv6ug9nph.apps.googleusercontent.com',
    iosBundleId: 'com.example.athletiShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp59BhrFWyjDtZbC2UJiXo4mSGwmCw_uw',
    appId: '1:74385235914:ios:637e1bbea89cc69204f933',
    messagingSenderId: '74385235914',
    projectId: 'athletic-shop',
    storageBucket: 'athletic-shop.appspot.com',
    androidClientId: '74385235914-o9avd5lqi7b42tf95k0afa5ao3gvl6m4.apps.googleusercontent.com',
    iosClientId: '74385235914-ufesth4ud9fbfue0kj6v6pel29ke6js1.apps.googleusercontent.com',
    iosBundleId: 'com.example.athletiShop.RunnerTests',
  );
}
